version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - env | grep AWS_DEFAULT_REGION
      - env | grep ECR_REPOSITORY_URI

  build:
    commands:
      - echo "Starting build phase..."
      - echo "AWS_DEFAULT_REGION in build: ${AWS_DEFAULT_REGION:-NOT_SET}"
      - echo "ECR_REPOSITORY_URI in build: ${ECR_REPOSITORY_URI:-NOT_SET}"

