  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - export AWS_DEFAULT_REGION=us-east-1  # Set the region if it's not available
      - echo "AWS_DEFAULT_REGION is set to: $AWS_DEFAULT_REGION"

