version: 0.2
env:
  variables:
    ECR_REPO_URI: "203918847581.dkr.ecr.us-east-1.amazonaws.com/ecs-node-cicd"
    AWS_REGION: "us-east-1"
    ECS_CLUSTER: "ecs-node-cicd-cluster"    # Replace with your cluster name
    ECS_SERVICE: "ecs-nodejs-service"    # Replace with your service name

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
      - IMAGE_TAG=${COMMIT_HASH}-${TIMESTAMP}

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo "Forcing ECS deployment..."
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment --region $AWS_REGION
      - echo "Creating imagedefinitions.json..."
      - mkdir -p build
      - printf '[{"name":"ecs-nodejs-container","imageUri":"%s:%s"}]' $ECR_REPO_URI $IMAGE_TAG > build/imagedefinitions.json

artifacts:
  files:
    - build/imagedefinitions.json
