version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - |
        aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REPOSITORY_URI"
      - |
        COMMIT_HASH=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        export IMAGE_TAG="${COMMIT_HASH}-${TIMESTAMP}"
        echo "IMAGE_TAG set to: ${IMAGE_TAG}"

  build:
    commands:
      - echo "Skipping build phase for now..."

  post_build:
    commands:
      - echo "Creating deployment artifacts..."
      - mkdir -p build
      - |
        printf '[{"name":"ecs-nodejs-container","imageUri":"%s"}]' "$ECR_REPOSITORY_URI:$IMAGE_TAG" > build/imagedefinitions.json
      - echo "Verifying artifact file..."
      - ls -l build/
      - |
        if [ ! -s build/imagedefinitions.json ]; then
          echo "ERROR: imagedefinitions.json is empty or missing!"
          exit 1
        fi

artifacts:
  files:
    - "build/imagedefinitions.json"
  discard-paths: yes

