version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $(env | grep AWS_DEFAULT_REGION | cut -d= -f2) | docker login --username AWS --password-stdin $(env | grep ECR_REPOSITORY_URI | cut -d= -f2)

  build:
    commands:
      - echo "Skipping build phase for now..."

  post_build:
    commands:
      - echo "Creating deployment artifacts..."
      - mkdir -p build
      - printf '[{"name":"ecs-nodejs-container","imageUri":"%s"}]' "$(env | grep ECR_REPOSITORY_URI | cut -d= -f2):$IMAGE_TAG" > build/imagedefinitions.json
      - echo "Verifying artifact file..."
      - ls -l build/

artifacts:
  files:
    - "build/imagedefinitions.json"
  discard-paths: yes

