version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $(env | grep AWS_DEFAULT_REGION | cut -d= -f2) | docker login --username AWS --password-stdin $(env | grep ECR_REPOSITORY_URI | cut -d= -f2)

  build:
    commands:
      - echo "Skipping build phase for now..."

  post_build:
    commands:
      - echo "Skipping post-build phase for now..."

artifacts:
  files:
    - build/imagedefinitions.json
  discard-paths: yes
