version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"  # Update this to your region
    ECR_REPOSITORY: "ecs-node-cicd"  # Update this with your repository name

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ECR_LOGIN=$(aws ecr get-login-password --region $AWS_REGION)
      - echo $ECR_LOGIN | docker login --username AWS --password-stdin $ECR_REPOSITORY

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY .
      - docker tag $ECR_REPOSITORY:latest $ECR_REPOSITORY:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY:latest
      - echo Build completed successfully.

