version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 203918847581.dkr.ecr.us-east-1.amazonaws.com
      - echo Retrieving the latest commit hash...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)  # Get the current timestamp
      - IMAGE_TAG=${COMMIT_HASH}-${TIMESTAMP}

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ecs-node-cicd:$IMAGE_TAG .
      - echo Tagging the Docker image...
      - docker tag ecs-node-cicd:$IMAGE_TAG 203918847581.dkr.ecr.us-east-1.amazonaws.com/ecs-node-cicd:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 203918847581.dkr.ecr.us-east-1.amazonaws.com/ecs-node-cicd:$IMAGE_TAG
      - echo Creating imagedefinitions.json for ECS deployment...
      - printf '[{"name":"ecs-nodejs-container","imageUri":"203918847581.dkr.ecr.us-east-1.amazonaws.com/ecs-node-cicd:%s"}]' $IMAGE_TAG > imagedefinitions.json
      - echo Build process completed.

artifacts:
  files:
    - imagedefinitions.json

