version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
      - echo "ECR_REPOSITORY_URI: $ECR_REPOSITORY_URI"
      - echo "Checking AWS CLI version..."
      - aws --version

