version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
      - echo "ECR_REPOSITORY_URI: $ECR_REPOSITORY_URI"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo "Generating image tag..."

