version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
      - echo "ECR_REPOSITORY_URI: $ECR_REPOSITORY_URI"

