version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - bash -c 'echo "AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-NOT_SET}"'
      - bash -c 'echo "ECR_REPOSITORY_URI: ${ECR_REPOSITORY_URI:-NOT_SET}"'

  build:
    commands:
      - echo "Building process starts here..."
      - echo "Simulating build step"

  post_build:
    commands:
      - echo "Post-build phase completed successfully!"
      - echo "Pipeline setup is working fine."

artifacts:
  files:
    - "**/*"
  discard-paths: yes

