version: 0.2

phases:
  pre_build:
    commands:
      - echo "Retrieving AWS account ID..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com || { echo "ECR login failed"; exit 1; }

      - echo "Setting up environment variables..."
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION  # Use Git commit hash as image tag
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

      - echo "Image tag: $IMAGE_TAG"
      - echo "Repository URI: $REPO_URI"

  build:
    commands:
      - echo "Current Directory: $(pwd)"  # Print the current working directory
      - echo "Listing files in the current directory..."
      - ls -la  # List all files to confirm Dockerfile is present

      - echo "Building Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG . || { echo "Docker build failed"; exit 1; }

      - echo "Listing Docker images..."
      - docker images  # Display the list of built images

